### ISSUE TITLE
Zlib compressed data header is not always stripped

### ISSUE THREAD

**Issue by Aloisius** [SwiftcordApp/DiscordKit#35]
The zlib header is currently only stripped for default level compression (0x78 0x9C). When I try logging in however, I'm getting a response back with a header of (0x78 0xDA) which is best compression level. This causes the header not to be stripped and decompression silently fails resulting in whatever garbage was in memory then being sent to the JSON decoder.

I'm running this from swiftcord. From DecompressionEngine decompress(_ data: Data) -> Data:

```
lldb> e data.map { String(format: "%02x ", $0) }.joined()
(String) $R1 = "78 da 34 c9 41 0a 83 30 10 05 d0 bb fc 75 52 92 52 29 cc 55 8c c8 34 0e 55 48 a3 24 a3 a5 48 ee de 6e ba 7b f0 4e 28 28 ef 29 19 d4 3f d6 0d e4 9d c1 04 3a 31 0b 17 7d 08 eb b8 64 95 72 70 02 dd fc b5 fb fd a8 85 a3 80 7a f4 01 4f 56 79 f3 c7 6e 65 b2 7b b5 c2 55 bd 8d f6 9e bb 39 c0 9c 01 af 25 96 b5 06 90 bb b8 36 60 68 ed 0b 00 00 ff ff "
```

After I strip off the two byte header when the first two bytes == 0x78 0xda, decoding gives me the proper response:

```
lldb> e String(decoding: decompressed, as: UTF8.self)
$R24: String = "{\"t\":null,\"s\":null,\"op\":10,\"d\":{\"heartbeat_interval\":41250,\"_trace\":[\"[\\\"gateway-prd-us-east1-c-7n5h\\\",{\\\"micros\\\":0.0}]\"]}}"
```

**Comment by cryptoAlgorithm** [comment]
Resolved by 2d42c69cafe592300a1a9d3a307bf485294026c7, thanks for the contribution!
