### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ilgrandeanonimo** [SwiftcordApp/DiscordKit#38]
I was considering whether to continue learning Swift or learn Go, C or other languages and since I mainly deal with Discord and Minecraft I wanted to know if this project was active to understand if one day there will be a Swift API for Discord

**Comment by cryptoAlgorithm** [comment]
DiscordKit is definitely active - it's the backbone allowing Swiftcord and the upcoming revamp (still under wraps!) to communicate with Discord, so I intend to continue developing this for the foreseeable future. Responses to issues and activity might sometimes be spotty, which is unfortunately unavoidable for a project worked on mainly by me as a single developer, but I do try to contribute whenever time permits.

**Comment by cryptoAlgorithm** [comment]
I'd be closing this issue if there're no further concerns. Happy botting!
